{% set name = "google-cloud-firestore" %}
{% set version = "2.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-firestore-{{ version }}.tar.gz
  sha256: e61ae70229a6e532e439c8d16447a32024447f2ee4a2303fc4d054c258d6877f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - google-auth >=2.14.1,<3.0.0dev,!=2.24.0,!=2.25.0
    - python >=3.7
    - google-api-core >=1.34.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-cloud-core >=1.4.1,<3.0.0dev
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google.cloud.firestore
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/googleapis/python-firestore
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python Client for Google Cloud Firestore
  doc_url: https://googleapis.dev/python/firestore/latest/index.html
  dev_url: https://github.com/googleapis/python-firestore

extra:
  recipe-maintainers:
    - xylar
    - mitchellsuter
